version: "3.1"

services:
  db:
    image: postgis/postgis:16-3.4
#    command: [
#      'postgres',
#      '-c',
#      'logging_collector=on',
#      '-c',
#      'log_destination=stderr',
#      '-c',
#      'log_directory=logs',
#      '-c',
#      'log_filename=postgresql.log',
#      '-c',
#      'log_min_duration_statement=0',
#      '-c',
#      'log_line_prefix=%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h ',
#      '-c',
#      'log_checkpoints=on',
#      '-c',
#      'log_connections=on',
#      '-c',
#      'log_disconnections=on',
#      '-c',
#      'log_lock_waits=on',
#      '-c',
#      'log_temp_files=0',
#      '-c',
#      'log_autovacuum_min_duration=0',
#      '-c',
#      'log_error_verbosity=verbose',
#    ]
    container_name: teatmik-postgres
    restart: always
    environment:
      POSTGRES_USER: josill
      POSTGRES_PASSWORD: uptime_teamik
      POSTGRES_DB: uptime-teatmik
      PGDATA: /var/lib/postgresql/data/some_name/
    ports:
      - 5432:5432
    volumes:
      - ./postgres-logs:/var/lib/postgresql/data/logs/
      - ./postgres-data:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"
