---
version: "3.1"

services:
  db:
    image: postgres:16
    container_name: teatmik-postgres
    restart: always
    environment:
      POSTGRES_USER: josill
      POSTGRES_PASSWORD: uptime_teatmik
      POSTGRES_DB: uptime-teatmik
      PGDATA: /var/lib/postgresql/data/uptime-teatmik/
    ports:
      - 5432:5432
    volumes:
      - ./postgres-logs:/var/lib/postgresql/data/logs/
      - ./postgres-data:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teatmik-api
    ports:
      - "8080:80"
    depends_on:
      - db
